"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs"), os = require("node:os"), path = require("node:path");
process.env.FAM_DATA_DIR = fs.mkdtempSync(path.join(os.tmpdir(), "fam-ledger-"));
process.env.DATA_ENCRYPTION_KEY = "23".repeat(32);
const db = require("../lib/db"), fams = require("../lib/fams"), insights = require("../lib/child-insights");
const realNow = Date.now;
let now = Date.parse("2026-09-07T05:00:00Z");
Date.now = () => now;
test.after(() => { Date.now = realNow; db.flushSync(); });
const today = () => new Date(now + 7 * 3600000).toISOString().slice(0, 10);
const complete = (family, kid, part) => fams.awardDaily5(family, kid, { date: today(), part, status: "completed" });
test("permanent events survive replay, reopening, and cross-week retry; scopes isolated", () => {
  assert.equal(complete("dedup", "kid", "news").awarded, 6);
  assert.equal(complete("dedup", "kid", "news").awarded, 0);
  assert.equal(fams.awardDaily5("dedup", "kid", { date: "2026-09-06", part: "news", status: "completed" }).error !== undefined, true);
  const item = { id: "old", kidId: "kid", sourceUid: "sta-api:kid:1", status: "done" };
  assert.equal(fams.awardHomework("dedup", item).awarded, 5);
  assert.equal(fams.awardHomework("dedup", { ...item, id: "replacement" }).awarded, 0);
  assert.equal(fams.awardHomework("dedup", { ...item, sourceUid: undefined, moodleIdentity: { taskId: 1 } }).awarded, 0);
  assert.equal(fams.summary("dedup", "sibling").balance, 0);
  assert.equal(fams.summary("other", "kid").balance, 0);
  now += 7 * 86400000;
  assert.equal(fams.awardHomework("dedup", item).awarded, 0);
  now -= 7 * 86400000;
});
test("regular cap is exactly 300, extras excluded, and Bangkok week rolls Monday", () => {
  now = Date.parse("2026-09-07T05:00:00Z");
  for (let day = 0; day < 7; day++) {
    for (const part of ["news", "word", "puzzle", "bt", "quote"]) complete("cap", "kid", part);
    for (let i = 0; i < 3; i++) fams.awardHomework("cap", { id: `${day}-${i}`, kidId: "kid", status: "done" });
    fams.awardNewsComment("cap", { authorType: "kid", authorId: "kid", source: "news", body: "A long enough news reflection.", date: today() });
    fams.awardLesson("cap", "kid", `lesson-${day}`);
    if (day < 6) now += 86400000;
  }
  assert.equal(fams.summary("cap", "kid").weekly.earned, 300);
  assert.equal(fams.summary("cap", "kid").balance, 300);
  fams.syncHousePoints("cap", "kid", 2);
  assert.equal(fams.summary("cap", "kid").balance, 400);
  now = Date.parse("2026-09-13T17:00:00Z");
  assert.equal(fams.summary("cap", "kid").weekly.weekStart, "2026-09-14");
  assert.equal(fams.summary("cap", "kid").weekly.earned, 0);
  assert.equal(fams.awardHomework("cap", { id: "6-2", kidId: "kid", status: "done" }).awarded, 0);
});
test("school history backfills once and lower imports require explicit reset", () => {
  db.load().childInsights = { historic: { child: { schoolStats: { housePoints: 10 } } } };
  assert.equal(fams.summary("historic", "child").balance, 500);
  assert.equal(fams.summary("historic", "child").balance, 500);
  fams.syncHousePoints("historic", "child", 12);
  fams.syncHousePoints("historic", "child", 3);
  assert.equal(fams.summary("historic", "child").balance, 600);
  assert.equal(fams.summary("historic", "child").schoolPoints.resetPending, true);
  fams.confirmSchoolReset("historic", "child");
  assert.equal(fams.summary("historic", "child").balance, 750);
  assert.ok(fams.confirmSchoolReset("historic", "child").error);
  fams.syncHousePoints("historic", "child", 4);
  assert.equal(fams.summary("historic", "child").balance, 800);
  for (const value of [0.001, -1, Infinity, "4", NaN]) assert.ok(fams.syncHousePoints("historic", "child", value).error);
  assert.equal(fams.summary("historic", "child").balance, 800);
});
test("first lower sync preserves recorded high water and rejects excessive point precision", () => {
  db.load().childInsights.sync = { child: { schoolStats: { housePoints: 20, importedAt: "2026-09-01T00:00:00Z" } } };
  const payload = { housePoints: 2, attendance: null, punctual: null, canteenBalance: null, importedAt: "2026-09-02T00:00:00Z" };
  insights.saveSchoolStats("sync", "child", payload);
  assert.equal(fams.summary("sync", "child").balance, 1000);
  assert.equal(fams.summary("sync", "child").schoolPoints.resetPending, true);
  assert.ok(insights.saveSchoolStats("sync", "child", { ...payload, housePoints: 0.001, importedAt: "2026-09-03T00:00:00Z" }).error);
});
test("chore flow requires submit, approvals replay safely, and amounts are integers", () => {
  for (const amount of [0, -1, 0.5, 10001, "1", Infinity]) assert.ok(fams.createChore("chore", "kid", { title: "Help", amount }).error);
  const { chore } = fams.createChore("chore", "kid", { title: "Help", amount: 10000 });
  assert.ok(fams.approveChore("chore", "kid", chore.id).error);
  assert.ok(fams.submitChore("chore", "sibling", chore.id).error);
  fams.submitChore("chore", "kid", chore.id); fams.submitChore("chore", "kid", chore.id);
  fams.approveChore("chore", "kid", chore.id); fams.approveChore("chore", "kid", chore.id);
  const s = fams.summary("chore", "kid");
  assert.equal(s.balance, 10000); assert.equal(s.weekly.earned, 0); assert.equal(s.transactions.length, 1);
  s.transactions[0].amount = 0; s.chores[0].amount = 0;
  assert.equal(fams.summary("chore", "kid").balance, 10000);
  assert.equal(fams.summary("chore", "kid").chores[0].amount, 10000);
  assert.ok(fams.setGoal("chore", "kid", { name: "Bike", target: 0.5 }).error);
  fams.setGoal("chore", "kid", { name: "Bike", target: 12000 });
  assert.equal(fams.summary("chore", "kid").goal.target, 12000);
});
test("news thresholds, lesson caps, prototype identities and encrypted persistence", () => {
  assert.equal(fams.awardNewsComment("news", { authorType: "parent", authorId: "kid", source: "news", body: "A sufficiently lengthy reflection.", date: today() }).awarded, 0);
  assert.equal(fams.awardNewsComment("news", { authorType: "kid", authorId: "kid", source: "news", body: "short", date: today() }).awarded, 0);
  assert.equal(fams.awardLesson("news", "kid", "one").awarded, 2);
  assert.equal(fams.awardLesson("news", "kid", "two").awarded, 0);
  assert.deepEqual(fams.summary("news", "kid").completedLessons, ["one", "two"]);
  complete("__proto__", "constructor", "puzzle");
  assert.equal(fams.summary("__proto__", "constructor").balance, 6);
  assert.equal({}.transactions, undefined);
  db.flushSync(); assert.equal(db.isFileEncrypted(), true);
  assert.equal(fs.readFileSync(db.DB_FILE, "utf8").includes("transactions"), false);
});
test("real homework, encrypted news note, and Daily5 boundaries credit once", () => {
  const users = require("../lib/store"), families = require("../lib/family");
  const homework = require("../lib/homework"), notes = require("../lib/notes");
  const parent = users.createUser("fams-hook@example.com", "Parent");
  const family = families.createFamily(parent.id, "Hook family");
  const { kid } = families.addKid(family.id, parent.id, { name: "Child", grade: "6" });
  const { homework: item } = homework.addHomework(family.id, { kidId: kid.id, title: "Read", dueDate: today() });
  homework.updateHomework(family.id, item.id, { status: "done" });
  homework.updateHomework(family.id, item.id, { status: "todo" });
  homework.updateHomework(family.id, item.id, { status: "done" });
  const note = { authorType: "kid", authorId: kid.id, date: today(), source: "news", body: "I learned how the new discovery helps scientists." };
  notes.addNote(family.id, note); notes.addNote(family.id, note);
  const progress = { date: today(), part: "news", status: "completed" };
  insights.reportProgress(family.id, kid.id, progress);
  insights.reportProgress(family.id, kid.id, { ...progress, status: "started" });
  insights.reportProgress(family.id, kid.id, progress);
  const result = fams.summary(family.id, kid.id);
  assert.equal(result.balance, 15);
  assert.equal(result.transactions.length, 3);
  assert.equal(result.balance, result.transactions.reduce((n, t) => n + t.amount, 0));
  assert.ok(db.load().fams[family.id][kid.id].transactions.every(t => Number.isSafeInteger(t.units)));
});
test("equal or older school timestamps cannot alternate high and low snapshots", () => {
  const payload = { housePoints: 10, attendance: null, punctual: null, canteenBalance: null, importedAt: "2026-09-01T00:00:00Z" };
  insights.saveSchoolStats("replay", "kid", payload);
  insights.saveSchoolStats("replay", "kid", { ...payload, housePoints: 1 });
  assert.equal(fams.summary("replay", "kid").schoolPoints.resetPending, false);
  insights.saveSchoolStats("replay", "kid", { ...payload, housePoints: 1, importedAt: "2026-09-02T00:00:00Z" });
  fams.confirmSchoolReset("replay", "kid");
  insights.saveSchoolStats("replay", "kid", payload);
  assert.ok(fams.confirmSchoolReset("replay", "kid").error);
  assert.equal(fams.summary("replay", "kid").balance, 550);
});

test("fractional school snapshots preserve hundredths and conserve ledger units", () => {
  const payload = { housePoints: 0.5, attendance: null, punctual: null, canteenBalance: null, importedAt: "2026-09-01T00:00:00Z" };
  assert.equal(insights.saveSchoolStats("fractional", "kid", payload).schoolStats.housePoints, 0.5);
  assert.equal(fams.summary("fractional", "kid").balance, 25);
  assert.equal(insights.saveSchoolStats("fractional", "kid", { ...payload, housePoints: 0.75, importedAt: "2026-09-02T00:00:00Z" }).schoolStats.housePoints, 0.75);
  assert.equal(fams.summary("fractional", "kid").balance, 37.5);
  assert.equal(fams.syncHousePoints("fractional", "kid", 0.75).awarded, 0);
  fams.syncHousePoints("fractional", "kid", 0.25);
  fams.confirmSchoolReset("fractional", "kid");
  assert.equal(fams.summary("fractional", "kid").balance, 50);
  fams.syncHousePoints("fractional", "kid", 0.29);
  assert.equal(fams.summary("fractional", "kid").balance, 52);
  const rows = db.load().fams.fractional.kid.transactions;
  assert.deepEqual(rows.map(t => t.units), [2500, 1250, 1250, 200]);
  assert.equal(rows.reduce((n, t) => n + t.units, 0), fams.summary("fractional", "kid").totalEarned * 100);
  db.load().childInsights.fractionalHistorical = { kid: { schoolStats: { housePoints: 0.25 } } };
  assert.equal(fams.summary("fractionalHistorical", "kid").balance, 12.5);
});

test("removing a child removes their rewards without touching siblings",()=>{
  const family=require("../lib/family");
  const f=family.createFamily("parent-delete","Delete fixture");
  const kid=family.addKid(f.id,"parent-delete",{name:"Child"}).kid;
  fams.setGoal(f.id,kid.id,{name:"Private child goal",target:20});
  fams.setGoal(f.id,"sibling",{name:"Keep me",target:30});
  family.removeKid(f.id,"wrong-parent",kid.id);
  assert.ok(Object.hasOwn(db.load().fams[f.id],kid.id));
  family.removeKid(f.id,"parent-delete",kid.id);
  assert.equal(Object.hasOwn(db.load().fams[f.id],kid.id),false);
  assert.equal(db.load().fams[f.id].sibling.goal.name,"Keep me");
});
