import XCTest
@testable import FamETC

final class FamsProjectionTests: XCTestCase {
    // Expected values generated by lib/finance-learning.js under Node v24.19.0.
    func testZeroRateConservesContributions() throws {
        let result = try XCTUnwrap(FamsProjection.calculate(principal: 100, monthlyContribution: 50, annualRate: 0, years: 1))
        XCTAssertEqual(result.total, 700)
        XCTAssertEqual(result.contributions, 700)
        XCTAssertEqual(result.growth, 0)
    }
    func testContributionsArriveAfterMonthlyGrowth() throws {
        let result = try XCTUnwrap(FamsProjection.calculate(principal: 0, monthlyContribution: 100, annualRate: 12, years: 1))
        XCTAssertEqual(result.total, 1268.25)
        XCTAssertEqual(result.contributions, 1200)
        XCTAssertEqual(result.growth, 68.25)
    }
    func testOneYearServerParity() throws {
        let result = try XCTUnwrap(FamsProjection.calculate(principal: 100, monthlyContribution: 50, annualRate: 10, years: 1))
        XCTAssertEqual(result.total, 738.75)
        XCTAssertEqual(result.contributions, 700)
        XCTAssertEqual(result.growth, 38.75)
    }
    func testMultipleYearServerParity() throws {
        let result = try XCTUnwrap(FamsProjection.calculate(principal: 500, monthlyContribution: 25, annualRate: 6, years: 3))
        XCTAssertEqual(result.total, 1581.74)
        XCTAssertEqual(result.contributions, 1400)
        XCTAssertEqual(result.growth, 181.74)
        XCTAssertEqual(result.series.map(\.year), [0, 1, 2, 3])
        XCTAssertEqual(result.series.map(\.total), [500, 839.23, 1199.38, 1581.74])
        XCTAssertEqual(result.series.map(\.contributions), [500, 800, 1100, 1400])
    }
    func testNegativeReturnServerParity() throws {
        let result = try XCTUnwrap(FamsProjection.calculate(principal: 100, monthlyContribution: 0, annualRate: -50, years: 1))
        XCTAssertEqual(result.total, 60.01)
        XCTAssertEqual(result.contributions, 100)
        XCTAssertEqual(result.growth, -39.99)
        XCTAssertEqual(result.series.map(\.total), [100, 60.01])
    }
    func testInvalidInputsAreRejected() {
        for invalid in [-1.0, .infinity, -.infinity, .nan] {
            XCTAssertNil(FamsProjection.calculate(principal: invalid, monthlyContribution: 0, annualRate: 0, years: 1))
            XCTAssertNil(FamsProjection.calculate(principal: 0, monthlyContribution: invalid, annualRate: 0, years: 1))
        }
        for invalid in [-50.1, 30.1, .infinity, -.infinity, .nan] {
            XCTAssertNil(FamsProjection.calculate(principal: 0, monthlyContribution: 0, annualRate: invalid, years: 1))
        }
        XCTAssertNil(FamsProjection.calculate(principal: 10_000_000.01, monthlyContribution: 0, annualRate: 0, years: 1))
        XCTAssertNil(FamsProjection.calculate(principal: 0, monthlyContribution: 1_000_000.01, annualRate: 0, years: 1))
        for invalid in [0, 51, Int.min, Int.max] {
            XCTAssertNil(FamsProjection.calculate(principal: 0, monthlyContribution: 0, annualRate: 0, years: invalid))
        }
        XCTAssertNotNil(FamsProjection.calculate(principal: 10_000_000, monthlyContribution: 1_000_000, annualRate: 30, years: 50))
    }
}
